# Generated by Django 5.1.2 on 2024-10-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontact',
            name='supplier',
        ),
    ]
