# Generated by Django 5.1.2 on 2024-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_address_user_remove_document_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome'),
        ),
    ]
