# Generated by Django 5.1.2 on 2024-10-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
    ]
