# Generated by Django 5.1.2 on 2024-10-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_notification_destination_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome do produto'),
        ),
    ]
