# Generated by Django 5.1.2 on 2024-11-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_stock_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexit',
            name='description',
        ),
    ]
