# Generated by Django 5.1.2 on 2024-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_stockexit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade máxima'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minimal_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade minima'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade'),
        ),
    ]
