services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - production-front
      - production-back
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - app-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metatron -d stockwise"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_DB: stockwise
      POSTGRES_USER: metatron
      POSTGRES_PASSWORD: 199718
    networks:
      - production-back

volumes:
  app-data:

networks:
  production-front:
    external: true
  production-back:
    external: true
